irasaneh/VOD/urls.py
from django.urls import path
from .views import *


app_name = "VOD"

urlpatterns = [
    path('', ResanehList.as_view(), name='list'),
    path('<int:pk>', ResanehDetail.as_view(), name='detail'),

    path('advideo/', AdVideoList.as_view(), name='list-video'),
    path('advideo/<int:pk>', AdVideoDetail.as_view(), name='detail-video'),
    path('adbox/', AdBoxList.as_view(), name='list-box'),
    path('adbox/<int:pk>', AdBoxDetail.as_view(), name='detail-box'),
    path('adevent/', AdEventList.as_view(), name='list-event'),
    path('adevent/<int:pk>', AdEventDetail.as_view(), name='detail-event'),

    path('AdConnectionLog/', AdConnectionLogPost.as_view(), name='AdConnectionLog'),
    path('AdApplicationLog/', AdApplicationLogPost.as_view(), name='AdApplicationLog'),
    path('AdVideoLog/', AdVideoLogPost.as_view(), name='AdVideoLog'),
    path('AdVideoCounterLog/', AdVideoCounterLogPost.as_view(), name='AdVideoCounterLog'),

    path('AdMyBox/<int:pk>', AdMyBox.as_view(), name='AdMyBox'),
    path('AdMyResanehs/<str:phone>', AdMyResanehs.as_view(), name='AdMyResanehs'),
    # path('AdMyResanehs/<int:pk>', AdMyResanehs.as_view(), name='AdMyResanehs'),
    path('test/', testapi, name='test'),



]

irasaneh/config/urls.py
from django.contrib import admin
from django.urls import path, include
from rest_framework_simplejwt import views as jwt_views

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('home.urls')),
    path('mblog/', include('blog.urls')),
    path('account/', include('account.urls')),
    path('resaneh/', include('resaneh.urls')),
    path('dashboard/', include('dashboard.urls')),
    path('cities/', include('cities.urls')),
    path('summernote/', include('django_summernote.urls')),
    path('comment/', include('comment.urls')),
    path('ratings/', include('star_ratings.urls', namespace='ratings')),
    path('api-auth/', include('rest_framework.urls')),

    path('VOD/', include('VOD.urls')),
    path('VOD/token/', jwt_views.TokenObtainPairView.as_view(), name='token_obtain_pair'),
    path('VOD/token/refresh/', jwt_views.TokenRefreshView.as_view(), name='token_refresh'),

]


#در حالت دپلوی غیرفعال بشه
from django.conf import settings
from django.conf.urls.static import static

urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

irasaneh/hitcount/urls.py
from django.urls import path

from hitcount.views import HitCountJSONView

app_name = 'hitcount'

urlpatterns = [
    path('hit/ajax/', HitCountJSONView.as_view(), name='hit_ajax'),
]

irasaneh/resaneh/urls.py
from django.urls import path
from .views import *

app_name = "resaneh"
urlpatterns = [
    path('', resaneh, name='resaneh'),
    path('page/<int:page>', resaneh, name='resaneh'),
    path('<slug:slug>', resaneh, name='resaneh'),
    path('<slug:slug>/page/<int:page>', resaneh, name='resaneh'),
    path('details/<slug:slug>', details, name='details'),
    # path('category/<slug:slug>', category, name='category'),
    # path('category/<slug:slug>/page/<int:page>', category, name='category'),
    # path('search/', search, name='search'),
    # path('search/page/<int:page>', search, name='search'),
    path('ajax/search-similars/', search_similars, name='ajax_search_similars'),


    path('comparison/', comparison, name='comparison'),
    path('comparison/<slug:slug1>', comparison, name='comparison'),
    path('comparison/<slug:slug1>/<slug:slug2>', comparison, name='comparison'),
    path('comparison/<slug:slug1>/<slug:slug2>/<slug:slug3>', comparison, name='comparison'),
    path('comparison/<slug:slug1>/<slug:slug2>/<slug:slug3>/<slug:slug4>', comparison, name='comparison'),
]

irasaneh/resaneh/forms.py
from django import forms
from .models import Resaneh
from location_field.forms.plain import PlainLocationField
from django.forms import HiddenInput

class LocationForm(forms.ModelForm):
    class Meta:
        model = Resaneh
        fields = ['location']


class DigitalResanehFrom(forms.ModelForm):
    # def __init__(self, *args, **kwargs):
    #     super(DigitalResanehFrom, self).__init__(*args, **kwargs)
    #     self.fields['creator'].widget.attrs['disabled'] = True
    # def __init__(self, *args, **kwargs):
    #
    #     super(DigitalResanehFrom, self).__init__(*args, **kwargs)
    #     self.fields['creator'].initial = request.user
        # user = self.instance.user

    class Meta:
        model = Resaneh
        fields = ['creator', 'company', 'place','name', 'slug','owner', 'country', 'state', 'city', 'zone','address','location','nvisit','price','detail','point','status','code','connectionID','publish','industry','tag','category','is_digital','tvModel','tvSize','is_Androidbox','androidVersion','operatorNumber']
        widgets={'creator': HiddenInput()}

irasaneh/resaneh/views.py
from django.shortcuts import render, get_object_or_404
from django.http import HttpResponse
from .models import Resaneh, Category
from django.core.paginator import Paginator
from .forms import LocationForm
from django.db.models import Q, Max, Min
from .filters import ResanehFilter, ResanehSearchFilter
from urllib.parse import urlencode
from hitcount.utils import get_hitcount_model
from hitcount.views import HitCountMixin
from cities.models import Country
from django.core import serializers
from json import dumps
# Create your views here.
def resaneh(request, slug=None, page=1):
    if slug:
        category = get_object_or_404(Category, slug=slug, status=True)
        resaneh_list = category.resaneh.filter(status="p", is_digital=False).order_by('-publish')

    else:
        category = None
        resaneh_list = Resaneh.objects.filter(status="p", is_digital=False).order_by('-publish')

    filter = ResanehFilter(request.GET, queryset=resaneh_list)
    resaneh_list = filter.qs

    paginator = Paginator(resaneh_list,16)
    resanehs = paginator.get_page(page)

    min_price = Resaneh.objects.aggregate(price=Min('price'))
    min_price = int(min_price['price'])
    max_price = Resaneh.objects.aggregate(price=Max('price'))
    max_price = int(max_price['price'])

    data = request.GET.copy()
    if 'page' in data:
        del data['page']

    countries = Country.objects.all()
    context ={
        "category" : category,
        "resanehs" : resanehs,
        "filter" : filter,
        "min_price" : min_price,
        "max_price" : max_price,
        "data" : urlencode(data),
        "countries" : countries,

        }
    return render(request,"resaneh/resaneh.html", context)



# def category(request,slug,page=1):
#     pass
#     category = get_object_or_404(Category, slug=slug, status=True)
#     resanehs_list = category.resaneh.filter(status="p").order_by('-publish')
#     paginator = Paginator(resanehs_list,2)
#     resanehs = paginator.get_page(page)
#
#     context = {
#         "category" : category,
#         "resanehs" : resanehs,
#
#     }
#     return render(request,"resaneh/category.html", context)


def details(request, slug):
    resaneh = get_object_or_404(Resaneh, slug=slug, status="p",is_digital=False)
    place = resaneh.place
    loc = resaneh.location
    loc = loc.split(",")
    print(loc)
    count_hit = True
    # print(place)
    lastresanehs = Resaneh.objects.filter(status="p", place=place,is_digital=False).order_by('-publish').exclude(id=resaneh.id)[:5]
    form = LocationForm()


    context ={
    "resaneh" : resaneh,
    "form" : form,
    "lastresanehs" : lastresanehs,
    "loc" : loc,
    }
    # hitcount logic
    hit_count = get_hitcount_model().objects.get_for_object(resaneh)
    hits = hit_count.hits
    hitcontext = context['hitcount'] = {'pk': hit_count.pk}
    hit_count_response = HitCountMixin.hit_count(request, hit_count)
    if hit_count_response.hit_counted:
        hits = hits + 1
        hitcontext['hit_counted'] = hit_count_response.hit_counted
        hitcontext['hit_message'] = hit_count_response.hit_message
        hitcontext['total_hits'] = hits
    return render(request, "resaneh/details.html", context)


def comparison(request, slug1=None, slug2=None, slug3=None, slug4=None):
    resanehs =[]
    if slug1:
        resaneh1 = Resaneh.objects.get(slug=slug1)
        category = resaneh1.category.all()
        resanehs.append(resaneh1)
        # resanehs["resaneh1"] = resaneh1
        if slug2:
            resaneh2 = Resaneh.objects.get(slug=slug2)
            # resanehs["resaneh2"] = resaneh2
            if resaneh2 not in resanehs:
                resanehs.append(resaneh2)
            if slug3:
                resaneh3 = Resaneh.objects.get(slug=slug3)
                # resanehs["resaneh3"] = resaneh3
                if resaneh3 not in resanehs:
                    resanehs.append(resaneh3)
                if slug4:
                    resaneh4 = Resaneh.objects.get(slug=slug4)
                    # resanehs["resaneh4"] = resaneh4
                    if resaneh4 not in resanehs:
                        resanehs.append(resaneh4)

    similars = Resaneh.objects.filter(category__in=category, status="p",is_digital=False)
    category = serializers.serialize('json', category)

    context = {
        "resanehs" : resanehs,
        "similars" : similars,
        "category" : category,


    }
    return render(request, "resaneh/comparison.html", context)




def search_similars(request):
    search = request.GET.get('q')
    category = request.GET.get('category')
    category = category.split(",")

    similars = Resaneh.objects.filter(Q(detail__icontains = search)| Q(address__icontains = search)| Q(name__icontains = search) | Q(point__icontains = search) | Q(company__name__icontains = search), status="p", is_digital=False, category__id__in=category)
    context = {
        "similars" : similars,
        "search" : search,
    }
    return render(request,"resaneh/search_similars.html", context)

irasaneh/resaneh/templates/resaneh/partials/category_loop.html
<ul class="dropdown-menu dropdown-submenu dropdown-submenu-left">
  {% for cat in cat.children.active %}
  <li>
    <a class="dropdown-item" href="{% url 'resaneh:resaneh' cat.slug %}"> {{cat.title}} {% if cat.children.active %} &raquo;{% endif %} </a>
    {%if cat.children.active %}
    {% include 'resaneh/partials/category_loop.html' %}
  {% endif %}
  {% endfor %}
</ul>

irasaneh/resaneh/templates/resaneh/partials/offer.html
{% if offer != None %}
<div class="block-21 mb-4 d-flex">
  <a href="{% url 'resaneh:details' offer.slug %}" class="blog-img mr-4" style="background-image:url('{{offer.resanehimage.first.image.url}}')"></a>
  <div class="text">
    <h3 class="heading"><a href="{% url 'resaneh:details' offer.slug %}">{{offer.name}}</a></h3>
    <div class="meta">
      <div><a href="#"><span class="fa fa-map-marker"> </span> {{offer.address}}</a></div>
      <div><a href="#"><span class="fa fa-industry"></span> {{offer.company}}</a></div>
      <div><a href="#"><span class="fa fa-flag"></span>
          {% if offer.category.all %}
          {% for category in offer.category.all %}
          <span>
            {{ category }}
            {% if forloop.counter < offer.category.all.count %}
            ،
            {% endif %}
          </span>
          {% endfor %}
          {% endif %}
        </a></div>
    </div>
  </div>
</div>
{% endif %}

irasaneh/resaneh/templates/resaneh/partials/resaneh_category_sidebar.html
<nav class="navbar navbar-expand-lg navbar-light bg-light mb-4">
  <div class="container-fluid">
    <a class="navbar-brand" style="font-size:18px;">دسته‌بندی‌ها:</a>
    <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target="#navbarSupportedContent" aria-controls="navbarSupportedContent" aria-expanded="false" aria-label="Toggle navigation">
      <span class="navbar-toggler-icon"></span>
    </button>
    <div class="collapse navbar-collapse" id="navbarSupportedContent">
      <ul class="navbar-nav ms-auto">

        <!-- Dropdown -->
        {% for cat in category %}
        {% if cat.parent == None %}
        <li class="nav-item dropdown ">
          <a class="nav-link {%if cat.children.active %} dropdown-toggle {% endif %}" href="{% url 'resaneh:resaneh' cat.slug %}" id="navbarDropdownMenuLinkRight-{{cat.title}}" role="button" data-mdb-toggle="dropdown" aria-expanded="false">
            {{cat.title}}
          </a>

          {%if cat.children.active %}
          <ul class="dropdown-menu" aria-labelledby="navbarDropdownMenuLinkRigh-{{cat.title}}t">
            {% for cat in cat.children.active %}

            <li>
              <a class="dropdown-item" href="{% url 'resaneh:resaneh' cat.slug %}"> {{cat.title}} {% if cat.children.active %} &raquo;{% endif %} </a>

              {%if cat.children.active %}
              {% include 'resaneh/partials/category_loop.html' %}
              {% endif %}
              {% endfor %}
            </li>

          </ul>
          {% endif %}
        </li>


        {% endif %}
        {% endfor %}
      </ul>
    </div>
  </div>
</nav>