irasaneh/VOD/urls.py
from django.urls import path
from .views import *


app_name = "VOD"

urlpatterns = [
    path('', ResanehList.as_view(), name='list'),
    path('<int:pk>', ResanehDetail.as_view(), name='detail'),

    path('advideo/', AdVideoList.as_view(), name='list-video'),
    path('advideo/<int:pk>', AdVideoDetail.as_view(), name='detail-video'),
    path('adbox/', AdBoxList.as_view(), name='list-box'),
    path('adbox/<int:pk>', AdBoxDetail.as_view(), name='detail-box'),
    path('adevent/', AdEventList.as_view(), name='list-event'),
    path('adevent/<int:pk>', AdEventDetail.as_view(), name='detail-event'),

    path('AdConnectionLog/', AdConnectionLogPost.as_view(), name='AdConnectionLog'),
    path('AdApplicationLog/', AdApplicationLogPost.as_view(), name='AdApplicationLog'),
    path('AdVideoLog/', AdVideoLogPost.as_view(), name='AdVideoLog'),
    path('AdVideoCounterLog/', AdVideoCounterLogPost.as_view(), name='AdVideoCounterLog'),

    path('AdMyBox/<int:pk>', AdMyBox.as_view(), name='AdMyBox'),
    path('AdMyResanehs/<str:phone>', AdMyResanehs.as_view(), name='AdMyResanehs'),
    # path('AdMyResanehs/<int:pk>', AdMyResanehs.as_view(), name='AdMyResanehs'),
    path('test/', testapi, name='test'),



]

irasaneh/blog/urls.py
from django.urls import path
from .views import *

app_name = "blog"
urlpatterns = [
    path('', blog, name='blog'),
    path('page/<int:page>', blog, name='blog'),
    path('<slug:slug>', single, name="single") ,
    path('category/<slug:slug>', category, name='category'),
    path('category/<slug:slug>/page/<int:page>', category, name='category'),
    path('search/', search, name='search'),
    path('search/page/<int:page>', search, name='search'),
]

irasaneh/config/urls.py
from django.contrib import admin
from django.urls import path, include
from rest_framework_simplejwt import views as jwt_views

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('home.urls')),
    path('mblog/', include('blog.urls')),
    path('account/', include('account.urls')),
    path('resaneh/', include('resaneh.urls')),
    path('dashboard/', include('dashboard.urls')),
    path('cities/', include('cities.urls')),
    path('summernote/', include('django_summernote.urls')),
    path('comment/', include('comment.urls')),
    path('ratings/', include('star_ratings.urls', namespace='ratings')),
    path('api-auth/', include('rest_framework.urls')),

    path('VOD/', include('VOD.urls')),
    path('VOD/token/', jwt_views.TokenObtainPairView.as_view(), name='token_obtain_pair'),
    path('VOD/token/refresh/', jwt_views.TokenRefreshView.as_view(), name='token_refresh'),

]


#در حالت دپلوی غیرفعال بشه
from django.conf import settings
from django.conf.urls.static import static

urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

irasaneh/hitcount/urls.py
from django.urls import path

from hitcount.views import HitCountJSONView

app_name = 'hitcount'

urlpatterns = [
    path('hit/ajax/', HitCountJSONView.as_view(), name='hit_ajax'),
]

irasaneh/blog/models.py
from django.db import models
from account.models import CustomUser
from django.utils import timezone
from extensions.utils import jalali_converter
from django.utils.html import format_html
from django.contrib.contenttypes.fields import GenericRelation
from comment.models import Comment
from star_ratings.models import Rating



# Managers

class ArticleManager(models.Manager):
    def published(self):
        return self.filter(status='p')


class CategoryManager(models.Manager):
    def active(self):
        return self.filter(status=True)



# Create your models here.
class IPAddress(models.Model):
    ip_address = models.GenericIPAddressField(verbose_name='آدرس آی‌پی')



class Category(models.Model):
    parent = models.ForeignKey('self', default=None, null=True, blank=True, on_delete=models.SET_NULL ,related_name='children' ,verbose_name='زیرشاخه')
    title = models.CharField(max_length=200, verbose_name="عنوان دسته‌بندی")
    slug = models.SlugField(max_length=100, unique=True, verbose_name="آدرس دسته‌بندی")
    status = models.BooleanField(default=True, verbose_name="نمایش داده شود؟")
    position = models.IntegerField(verbose_name="پوزیشن")
    class Meta:
        verbose_name = "دسته‌بندی"
        verbose_name_plural = "دسته‌بندی‌ها"
        ordering = ['parent__id','position']

    def __str__(self):
        return self.title

    objects = CategoryManager()

class Article(models.Model):
    STATUS_CHOICES = (
        ('d', 'پیش‌نویس'),
        ('p', 'منتشر شده'),
    )
    author = models.ForeignKey(CustomUser, null=True, on_delete=models.SET_NULL, related_name="articles", verbose_name="نویسنده")
    title = models.CharField(max_length=200, verbose_name="تیتر خبر")
    slug = models.SlugField(max_length=100, unique=True, verbose_name="آدرس")
    category = models.ManyToManyField(Category, verbose_name="دسته‌بندی", related_name="articles")
    minidescription = models.CharField(max_length=500, verbose_name="خلاصه")
    description = models.TextField(verbose_name="متن")
    thumbnail = models.ImageField(upload_to="blogimages", verbose_name="تصویر")
    publish = models.DateTimeField(default=timezone.now, verbose_name="زمان انتشار")
    created = models.DateTimeField(auto_now_add=True)
    updated = models.DateTimeField(auto_now=True)
    status = models.CharField(max_length=1, choices=STATUS_CHOICES, verbose_name="وضعیت")
    comments = GenericRelation(Comment)
    hits = models.ManyToManyField(IPAddress, blank=True, related_name='hits', verbose_name='بازدیدها')
    ratings = GenericRelation(Rating, related_query_name='articles')
    # rate = models.DecimalField(max_digits=3, decimal_places=2, verbose_name="امتیاز", default=0.00)

    class Meta:
        verbose_name = "خبر"
        verbose_name_plural = "خبرها"

    def __str__(self):
        return self.title

    def jpublish(self):
        return jalali_converter(self.publish)
    jpublish.short_description = "زمان انتشار"

    def category_published(self):
        return self.category.filter(status=True)

    def thumbnail_tag(self):
        return format_html("<img style='width:55px;' src='{}'".format(self.thumbnail.url))
    thumbnail_tag.short_description = "تصویر"


# from django.db import models
# from django.utils import timezone
#
#
# # Create your models here.
# class Article(models.Model):
#     STATUS_CHOICES = (
#         ('d', 'draft'),
#         ('p', 'publish'),
#     )
#     title = models.CharField(max_length=200)
#     slug = models.SlugField(max_length=100, unique=True)
#     description = models.TextField()
#     thumbnail = models.ImageField(upload_to="blogimages")
#     publish = models.DateTimeField(default=timezone.now)
#     created = models.DateTimeField(auto_now_add=True)
#     updated = models.DateTimeField(auto_now=True)
#     status = models.CharField(max_length=1, choices=STATUS_CHOICES)
#
#     def __str__(self):
#         return self.title

irasaneh/blog/views.py
from django.shortcuts import render, get_object_or_404
from django.http import HttpResponse
from .models import Article, Category
from django.core.paginator import Paginator
from django.db.models import Q
from django.utils.translation import activate

# Create your views here.
def blog(request, page=1):
    articles_list = Article.objects.filter(status="p").order_by('-publish')
    paginator = Paginator(articles_list,15)
    # page = request.GET.get('page')
    articles = paginator.get_page(page)
    context ={
        "articles" : articles,
        # "rate" : rate_list,
        }
    return render(request,"blog/blog.html", context)
    # return render(request, "blog/blog.html")
    # return HttpResponse("blog")
#
def single(request,slug):

    article = get_object_or_404(Article, slug=slug, status="p")

    ip_address = request.user.ip_address
    if ip_address not in article.hits.all():
        article.hits.add(ip_address)

    lastarticles = Article.objects.filter(status="p").order_by('-publish').exclude(id=article.id)[:4]
    tags = Category.objects.filter(status=True).all()
    print(len(tags))
    context = {
        "article" : article,
        "lastarticles" : lastarticles,
        "tags" : tags,
    }
    return render(request,"blog/single.html", context)



def category(request,slug,page=1):
    category = get_object_or_404(Category, slug=slug, status=True)
    articles_list = category.articles.filter(status="p").order_by('-publish')
    paginator = Paginator(articles_list,15)
    articles = paginator.get_page(page)
    context = {
        "category" : category,
        "articles" : articles,
    }
    return render(request,"blog/category.html", context)


def search(request, page=1):
    search = request.GET.get('q')
    articles_list = Article.objects.filter(Q(minidescription__icontains = search) | Q(description__icontains = search) | Q(title__icontains = search), status="p").order_by('-publish')
    # articles_list = category.articles.filter(status="p").order_by('-publish')
    paginator = Paginator(articles_list,15)
    articles = paginator.get_page(page)
    context = {
        "articles" : articles,
        "search" : search,
    }
    return render(request,"blog/search.html", context)

irasaneh/blog/templates/blog/partials/blog_category_sidebar.html
<div class="col-3">
  <div class=" sidebar ftco-animate">
    <div class="sidebar-box">
      <form action="{% url 'blog:search' %}" class="search-form">
        <div class="form-group">
          <input type="text" class="form-control text-center" name='q' placeholder="جست و جو کنید">
          <button  class="fa fa-search" style="position:absolute; border:none; background-color:white; color:white;"><i class="bi bi-search" style="color:black;"></i></button>
        </div>
      </form>
    </div>
    <div class="sidebar-box ftco-animate">
      <div class="categories">
        <h3 class="text-center">دسته‌بندی‌ها</h3>
        <ul class="p-0">

          {% for cat in category %}
          {% if cat.parent == None %}
          <li>
            <div class="row d-flex justify-content-between">
              <div class="col-2">
                {%if cat.children.active %}
                <a href="#apps-{{cat.title}}" data-toggle="collapse" aria-expanded="false" class="">
                  <span class="fa fa-chevron-down"></span>
                </a>
                {% endif %}
              </div>
              <div class="col-10">
                <a href="{% url 'blog:category' cat.slug %}" class="text-center">{{cat.title}}</a>
              </div>
            </div>

            {%if cat.children.active %}
            {% include 'blog/partials/category_loop.html' %}
            {% endif %}
          </li>
          {% endif %}
          {% endfor %}

        </ul>


      </div>
    </div>
  </div>
</div>

irasaneh/blog/templates/blog/partials/category_loop.html
<ul class="collapse list-unstyled" id="apps-{{cat.title}}">
  {% for cat in cat.children.active %}
  <li>
    <div class="row d-flex justify-content-between">
      <div class="col-3">
        {%if cat.children.active %}
        <a href="#apps-{{cat.title}}" data-toggle="collapse" aria-expanded="false" class="">
          <span class="fa fa-chevron-down"></span>
        </a>
        {% endif %}
      </div>
      <div class="col-9">
        <a href="{% url 'blog:category' cat.slug %}" class="text-center">{{cat.title}}</a>
      </div>
    </div>
    {%if cat.children.active %}
      {% include 'blog/partials/category_loop.html' %}
    {% endif %}
  </li>
  {% endfor %}
</ul>