irasaneh/VOD/urls.py
from django.urls import path
from .views import *


app_name = "VOD"

urlpatterns = [
    path('', ResanehList.as_view(), name='list'),
    path('<int:pk>', ResanehDetail.as_view(), name='detail'),

    path('advideo/', AdVideoList.as_view(), name='list-video'),
    path('advideo/<int:pk>', AdVideoDetail.as_view(), name='detail-video'),
    path('adbox/', AdBoxList.as_view(), name='list-box'),
    path('adbox/<int:pk>', AdBoxDetail.as_view(), name='detail-box'),
    path('adevent/', AdEventList.as_view(), name='list-event'),
    path('adevent/<int:pk>', AdEventDetail.as_view(), name='detail-event'),

    path('AdConnectionLog/', AdConnectionLogPost.as_view(), name='AdConnectionLog'),
    path('AdApplicationLog/', AdApplicationLogPost.as_view(), name='AdApplicationLog'),
    path('AdVideoLog/', AdVideoLogPost.as_view(), name='AdVideoLog'),
    path('AdVideoCounterLog/', AdVideoCounterLogPost.as_view(), name='AdVideoCounterLog'),

    path('AdMyBox/<int:pk>', AdMyBox.as_view(), name='AdMyBox'),
    path('AdMyResanehs/<str:phone>', AdMyResanehs.as_view(), name='AdMyResanehs'),
    # path('AdMyResanehs/<int:pk>', AdMyResanehs.as_view(), name='AdMyResanehs'),
    path('test/', testapi, name='test'),



]

irasaneh/comment/urls.py
from django.urls import path, re_path
from django.views.decorators.cache import cache_page
from django.views.i18n import JavaScriptCatalog

from comment import __version__
from comment.views import (
    CreateComment, UpdateComment, DeleteComment, SetReaction, SetFlag, ChangeFlagState,
    ConfirmComment, ToggleFollowView, ToggleBlockingView
)

app_name = 'comment'


urlpatterns = [
    path('create/', CreateComment.as_view(), name='create'),
    path('edit/<int:pk>/', UpdateComment.as_view(), name='edit'),
    path('delete/<int:pk>/', DeleteComment.as_view(), name='delete'),
    path('<int:pk>/react/<str:reaction>/', SetReaction.as_view(), name='react'),
    path('<int:pk>/flag/', SetFlag.as_view(), name='flag'),
    path('<int:pk>/flag/state/change/', ChangeFlagState.as_view(), name='flag-change-state'),
    re_path(r'^confirm/(?P<key>[^/]+)/$', ConfirmComment.as_view(), name='confirm-comment'),
    path('toggle-subscription/', ToggleFollowView.as_view(), name='toggle-subscription'),
    path('toggle-blocking/', ToggleBlockingView.as_view(), name='toggle-blocking'),
    # javascript translations
    # The value returned by _get_version() must change when translations change.
    path(
        'jsi18n/',
        cache_page(86400, key_prefix='js18n-%s' % __version__)(JavaScriptCatalog.as_view()),
        name='javascript-catalog'),
]

irasaneh/config/urls.py
from django.contrib import admin
from django.urls import path, include
from rest_framework_simplejwt import views as jwt_views

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('home.urls')),
    path('mblog/', include('blog.urls')),
    path('account/', include('account.urls')),
    path('resaneh/', include('resaneh.urls')),
    path('dashboard/', include('dashboard.urls')),
    path('cities/', include('cities.urls')),
    path('summernote/', include('django_summernote.urls')),
    path('comment/', include('comment.urls')),
    path('ratings/', include('star_ratings.urls', namespace='ratings')),
    path('api-auth/', include('rest_framework.urls')),

    path('VOD/', include('VOD.urls')),
    path('VOD/token/', jwt_views.TokenObtainPairView.as_view(), name='token_obtain_pair'),
    path('VOD/token/refresh/', jwt_views.TokenRefreshView.as_view(), name='token_refresh'),

]


#در حالت دپلوی غیرفعال بشه
from django.conf import settings
from django.conf.urls.static import static

urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

irasaneh/hitcount/urls.py
from django.urls import path

from hitcount.views import HitCountJSONView

app_name = 'hitcount'

urlpatterns = [
    path('hit/ajax/', HitCountJSONView.as_view(), name='hit_ajax'),
]

irasaneh/comment/models/followers.py
from django.contrib.contenttypes.models import ContentType
from django.contrib.contenttypes.fields import GenericForeignKey
from django.db import models

from comment.managers.followers import FollowerManager


class Follower(models.Model):
    email = models.EmailField()
    username = models.CharField(max_length=50)
    content_type = models.ForeignKey(ContentType, on_delete=models.CASCADE)
    object_id = models.PositiveIntegerField()
    content_object = GenericForeignKey()

    class Meta:
        verbose_name = "دنبال‌کننده"
        verbose_name_plural = "دنبال‌کننده‌ها"

    objects = FollowerManager()

    def __str__(self):
        return f'{str(self.content_object)} followed by {self.email}'

    def __repr__(self):
        return self.__str__()

irasaneh/comment/api/views.py
from django.core.exceptions import ValidationError
from rest_framework import generics, permissions, status
from rest_framework.response import Response
from rest_framework.views import APIView

from comment.validators import ValidatorMixin, ContentTypeValidator
from comment.api.serializers import CommentSerializer, CommentCreateSerializer
from comment.api.permissions import (
    IsOwnerOrReadOnly, FlagEnabledPermission, CanChangeFlaggedCommentState, SubscriptionEnabled,
    CanGetSubscribers, CanCreatePermission, UserPermittedOrReadOnly, CanBlockUsers
)
from comment.models import Comment, Reaction, ReactionInstance, Flag, FlagInstance, Follower
from comment.utils import get_comment_from_key, CommentFailReason
from comment.messages import FlagError, EmailError
from comment.views import BaseToggleFollowView, CommentCreateMixin, BaseToggleBlockingView


class CommentCreate(ValidatorMixin, generics.CreateAPIView):
    serializer_class = CommentCreateSerializer
    permission_classes = (CanCreatePermission, UserPermittedOrReadOnly)
    api = True

    def get_serializer_context(self):
        self.validate(self.request)
        context = super().get_serializer_context()
        context['model_obj'] = self.model_obj
        context['parent_comment'] = self.parent_comment
        context['email'] = self.request.GET.get('email', None)
        return context


class CommentList(ContentTypeValidator, generics.ListAPIView):
    serializer_class = CommentSerializer
    permission_classes = (permissions.IsAuthenticatedOrReadOnly,)
    api = True

    def get_queryset(self):
        self.validate(self.request)
        return Comment.objects.filter_parents_by_object(self.model_obj).select_related('user', 'reaction', 'flag')


class CommentDetail(generics.RetrieveUpdateDestroyAPIView):
    queryset = Comment.objects.all().select_related('user', 'reaction', 'flag')
    serializer_class = CommentSerializer
    permission_classes = (permissions.IsAuthenticatedOrReadOnly, IsOwnerOrReadOnly, UserPermittedOrReadOnly)


class CommentDetailForReaction(generics.UpdateAPIView):
    queryset = Comment.objects.all().select_related('user', 'reaction', 'flag')
    serializer_class = CommentSerializer
    permission_classes = (permissions.IsAuthenticatedOrReadOnly, UserPermittedOrReadOnly)

    def get_serializer_context(self):
        context = super().get_serializer_context()
        context['reaction_update'] = True
        return context

    def post(self, request, *args, **kwargs):
        comment = self.get_object()
        reaction_type = kwargs.get('reaction', None)
        reaction_obj = Reaction.objects.get_reaction_object(comment)
        try:
            ReactionInstance.objects.set_reaction(
                user=request.user,
                reaction=reaction_obj,
                reaction_type=reaction_type
            )
        except ValidationError as e:
            return Response({'detail': e.messages}, status=status.HTTP_400_BAD_REQUEST)

        comment.reaction.refresh_from_db()
        serializer = self.get_serializer(comment)
        return Response(serializer.data, status=status.HTTP_200_OK)


class CommentDetailForFlag(generics.UpdateAPIView):
    queryset = Comment.objects.all().select_related('user', 'reaction', 'flag')
    serializer_class = CommentSerializer
    permission_classes = (permissions.IsAuthenticatedOrReadOnly, FlagEnabledPermission, UserPermittedOrReadOnly)

    def get_serializer_context(self):
        context = super().get_serializer_context()
        context['flag_update'] = True
        return context

    def post(self, request, *args, **kwargs):
        comment = self.get_object()
        flag = Flag.objects.get_for_comment(comment)
        reason = request.data.get('reason') or request.POST.get('reason')
        info = request.data.get('info') or request.POST.get('info')
        try:
            FlagInstance.objects.set_flag(request.user, flag, reason=reason, info=info)
        except ValidationError as e:
            return Response({'detail': e.messages}, status=status.HTTP_400_BAD_REQUEST)

        serializer = self.get_serializer(comment)
        return Response(serializer.data, status=status.HTTP_200_OK)


class CommentDetailForFlagStateChange(generics.UpdateAPIView):
    queryset = Comment.objects.all().select_related('user', 'reaction', 'flag')
    serializer_class = CommentSerializer
    permission_classes = (CanChangeFlaggedCommentState, UserPermittedOrReadOnly)

    def get_serializer_context(self):
        context = super().get_serializer_context()
        context['flag_update'] = True
        return context

    def post(self, request, *args, **kwargs):
        comment = self.get_object()
        flag = Flag.objects.get_for_comment(comment)
        state = request.data.get('state') or request.POST.get('state')
        try:
            state = flag.get_clean_state(state)
            if not comment.is_edited and state == flag.RESOLVED:
                return Response(
                    {'detail': FlagError.RESOLVE_UNEDITED_COMMENT},
                    status=status.HTTP_400_BAD_REQUEST
                )
            flag.toggle_state(state, request.user)
        except ValidationError as e:
            return Response({'detail': e.messages}, status=status.HTTP_400_BAD_REQUEST)

        serializer = self.get_serializer(comment)
        return Response(serializer.data, status=status.HTTP_200_OK)


class ConfirmComment(APIView, CommentCreateMixin):
    def get(self, request, *args, **kwargs):
        key = kwargs.get('key', None)
        temp_comment = get_comment_from_key(key)

        if temp_comment.why_invalid == CommentFailReason.BAD:
            return Response({'detail': EmailError.BROKEN_VERIFICATION_LINK}, status=status.HTTP_400_BAD_REQUEST)

        if temp_comment.why_invalid == CommentFailReason.EXISTS:
            return Response({'detail': EmailError.USED_VERIFICATION_LINK}, status=status.HTTP_200_OK)

        comment = self.perform_save(temp_comment.obj, request)

        return Response(CommentSerializer(comment).data, status=status.HTTP_201_CREATED)


class ToggleFollowAPI(BaseToggleFollowView, APIView):
    api = True
    response_class = Response
    permission_classes = (SubscriptionEnabled, permissions.IsAuthenticated, UserPermittedOrReadOnly)

    def post(self, request, *args, **kwargs):
        self.validate(request)
        return super().post(request, *args, **kwargs)


class SubscribersAPI(ContentTypeValidator, APIView):
    api = True
    permission_classes = (CanGetSubscribers,)

    def get(self, request, *args, **kwargs):
        self.validate(request)
        return Response({
            'app_name': self.model_obj._meta.app_label,
            'model_name': self.model_obj.__class__.__name__,
            'model_id': self.model_obj.id,
            'followers': Follower.objects.get_emails_for_model_object(self.model_obj)
        })


class ToggleBlockingAPI(BaseToggleBlockingView, APIView):
    permission_classes = (CanBlockUsers,)
    response_class = Response

irasaneh/comment/views/base.py
from django.views.generic import FormView

from comment.conf import settings
from comment.context import DABContext
from comment.responses import DABResponseData
from comment.messages import EmailInfo
from comment.service.email import DABEmailService
from comment.forms import CommentForm


class BaseCommentView(FormView, DABResponseData):
    form_class = CommentForm

    def get_context_data(self, **kwargs):
        context = super().get_context_data(**kwargs)
        context['comment_form'] = context.pop('form')
        context.update(DABContext(self.request))
        return context

    def get_form_kwargs(self):
        kwargs = super().get_form_kwargs()
        kwargs['request'] = self.request
        return kwargs


class CommentCreateMixin(BaseCommentView):
    email_service = None

    def _initialize_email_service(self, comment, request):
        self.email_service = DABEmailService(comment, request)

    def _send_notification_to_followers(self, comment, request):
        if settings.COMMENT_ALLOW_SUBSCRIPTION:
            self._initialize_email_service(comment, request)
            self.email_service.send_notification_to_followers()

    def perform_save(self, comment, request):
        comment.save()
        self._send_notification_to_followers(comment, request)
        comment.refresh_from_db()
        return comment

    def _handle_anonymous(self, comment, request, api=False):
        self._initialize_email_service(comment, request)
        self.email_service.send_confirmation_request(api=api)
        self.anonymous = True
        self.msg = EmailInfo.CONFIRMATION_SENT

    def perform_create(self, comment, request, api=False):
        if settings.COMMENT_ALLOW_ANONYMOUS and not comment.user:
            self._handle_anonymous(comment, request, api)
        else:
            comment = self.perform_save(comment, request)
        return comment

irasaneh/comment/views/blocker.py
from django.views import View

from comment.models import BlockedUser, BlockedUserHistory, Comment
from comment.mixins import CanBlockUsersMixin
from comment.responses import UTF8JsonResponse, DABResponseData
from comment.messages import BlockUserError


class BaseToggleBlockingView(DABResponseData):
    response_class = None

    def get_response_class(self):
        assert self.response_class is not None, (
                "'%s' should either include a `response_class` attribute, "
                "or override the `get_response_class()` method."
                % self.__class__.__name__
        )
        return self.response_class

    def post(self, request, *args, **kwargs):
        response_class = self.get_response_class()
        request_data = request.POST or getattr(request, 'data', {})
        comment_id = request_data.get('comment_id', None)
        try:
            comment = Comment.objects.get(id=int(comment_id))
        except (Comment.DoesNotExist, ValueError, TypeError):
            self.error = {
                'detail': BlockUserError.INVALID
            }
            self.status = 400
            return response_class(self.json(), status=self.status)

        blocked_user, created = BlockedUser.objects.get_or_create_blocked_user_for_comment(comment)

        if not created:
            blocked_user.blocked = not blocked_user.blocked
        blocked_user.save()

        reason = request_data.get('reason', None)
        if blocked_user.blocked and not reason:
            reason = comment.content

        BlockedUserHistory.objects.create_history(
            blocked_user=blocked_user,
            blocker=request.user,
            reason=reason
        )
        self.data = {
            'blocked_user': comment.get_username(),
            'blocked': blocked_user.blocked,
            'urlhash': comment.urlhash
        }
        return response_class(self.json())


class ToggleBlockingView(CanBlockUsersMixin, BaseToggleBlockingView, View):
    response_class = UTF8JsonResponse

irasaneh/comment/views/flags.py
from django.core.exceptions import ValidationError
from django.shortcuts import get_object_or_404
from django.views import View

from comment.models import Comment, Flag, FlagInstance
from comment.mixins import CanSetFlagMixin, CanUpdateFlagStateMixin, BaseCommentMixin
from comment.responses import UTF8JsonResponse, DABResponseData
from comment.messages import FlagInfo, FlagError


class SetFlag(CanSetFlagMixin, BaseCommentMixin, View, DABResponseData):
    comment = None

    def get_object(self):
        self.comment = get_object_or_404(
            Comment.objects.select_related('user', 'reaction', 'flag'),
            pk=self.kwargs.get('pk')
        )
        return self.comment

    def post(self, request, *args, **kwargs):
        self.data = {
            'status': 1
        }
        flag = Flag.objects.get_for_comment(self.comment)

        try:
            if FlagInstance.objects.set_flag(request.user, flag, **request.POST.dict()):
                self.msg = FlagInfo.FLAGGED_SUCCESS
                self.data['flag'] = 1
            else:
                self.msg = FlagInfo.UNFLAGGED_SUCCESS

            self.data.update({'status': 0})
            self.status = 200
        except ValidationError as e:
            self.error = e.message
            self.status = 400

        return UTF8JsonResponse(self.json(), status=self.status)


class ChangeFlagState(CanUpdateFlagStateMixin, View, DABResponseData):
    comment = None

    def get_object(self):
        self.comment = get_object_or_404(
            Comment.objects.select_related('user', 'reaction', 'flag'),
            pk=self.kwargs.get('pk')
        )
        return self.comment

    def post(self, request, *args, **kwargs):
        state = request.POST.get('state')
        try:
            self.comment.flag.toggle_state(state, request.user)
            self.status = 200
        except ValidationError:
            self.error = FlagError.STATE_CHANGE_ERROR
            self.status = 400

        self.data = {
            'state': self.comment.flag.state
        }
        return UTF8JsonResponse(self.json(), status=self.status)

irasaneh/comment/templates/comment/comments/apply_icon.html
<button class="{% block apply_btn_cls %}btn btn-link{% endblock apply_btn_cls %}" type="submit" name="form_type">
{% block apply_img_icon %}
<svg xmlns="http://www.w3.org/2000/svg" width="18" height="18" viewBox="0 0 24 24"
        fill="none" stroke="{% block apply_icon_color %}#00bc8c{% endblock apply_icon_color %}" stroke-width="2" stroke-linecap="round"
        stroke-linejoin="round" class="feather feather-check">
    <polyline points="20 6 9 17 4 12"></polyline>
</svg>
{% endblock apply_img_icon %}
</button>

irasaneh/comment/templates/comment/comments/cancel_icon.html
<a class="js-comment-cancel {% block cancel_btn_cls %}btn btn-link{% endblock cancel_btn_cls %}" href="#">
{% block cancel_img_icon %}
<svg xmlns="http://www.w3.org/2000/svg" width="18" height="18" viewBox="0 0 24 24"
     fill="none" stroke="{% block cancel_icon_color %}#E74C3C{% endblock cancel_icon_color %}" stroke-width="2" stroke-linecap="round" stroke-linejoin="round" class="feather feather-x">
    <line x1="18" y1="6" x2="6" y2="18"></line><line x1="6" y1="6" x2="18" y2="18"></line>
</svg>
{% endblock cancel_img_icon %}
</a>

irasaneh/comment/templates/comment/comments/child_comment.html
<div class="js-child-comment {% block child_comment_wrapper_cls %}text-wrap mb-4{% endblock child_comment_wrapper_cls %}">
    <hr/>
    {% include 'comment/comments/comment_body.html' with comment=comment %}
</div>

irasaneh/comment/templates/comment/comments/comment_modal.html
{% load i18n %}
{% load comment_tags %}
<form class="js-comment-delete-form m-0" data-url="{% if comment %}{% url 'comment:delete' pk=comment.id %}{% endif %}">
    {% csrf_token %}
    <div class="modal-header">
        <h5 class="modal-title comment-translatable">{% block title %}{% trans "Confirm comment deletion" %}{% endblock title %}</h5>
        <button type="button" class="modal-close-btn" aria-label="{% trans "Close" %}">
            <span aria-hidden="true">&times;</span>
        </button>
    </div>
    <div class="modal-body">
        <p class="lead comment-translatable">{% block content %}{% trans "Are you sure you want to delete this comment" %}{% endblock content %} <strong>"{{ comment.content|slice:":25" }}"</strong>؟</p>
    </div>
    <div class="modal-footer">
        <button type="button" class="ml-2 comment-translatable modal-cancel-btn {% block close_btn_cls %}btn btn-secondary{% endblock close_btn_cls %}" data-dismiss="modal">{% trans "Close" %}</button>
        <input name="model_name" value="{{model_name}}" hidden>
        <input name="model_id" value="{{model_id}}" hidden>
        <input name="app_name" value="{{app_name}}" hidden>
        <input name="isParent" value="{{comment.is_parent}}" hidden>
        <input name="oauth" value="{{oauth}}" hidden>
        <button id="modal-btn" type="submit" class="{% block del_btn_cls %}btn btn-danger{% endblock del_btn_cls %}">
            <span class="comment-translatable">{% trans "Delete" %}</span>
        </button>
    </div>
</form>

irasaneh/comment/templates/comment/comments/content.html
{% load i18n %}
<p class="js-comment-content {% block content_text_cls %}mb-0{% endblock content_text_cls %}">
    {% block comment_urlhash %}
    {% include "comment/comments/urlhash.html" with urlhash=urlhash %}
    {% endblock comment_urlhash %}
    {% if text_2 %}
        {{ text_1 }}
        <span class="d-none">{{ text_2 }}</span>
        <button class="js-read-more-btn {% block read_more_cls %}btn btn-link btn-xs read-more{% endblock read_more_cls %}">{% trans "read more" %}...</button>
    {% else %}
        {{ text_1 }}
    {% endif %}
</p>

irasaneh/comment/templates/comment/comments/delete_icon.html
{% load comment_tags %}
{% load i18n %}
<button title="{% trans 'Delete comment' %}" class="js-comment-delete {% block delete_btn_cls %}btn btn-link{% endblock delete_btn_cls %}" data-url="{% url 'comment:delete' pk=comment.id %}?model_name={% get_model_name model_object %}&model_id={{ model_object.id }}&app_name={% get_app_name model_object %}&oauth={{oauth}}">
{% block delete_img_icon %}
<svg xmlns="http://www.w3.org/2000/svg" width="18" height="18" viewBox="0 0 24 24"
     fill="none" stroke="{% block delete_icon_color %}#E74C3C{% endblock delete_icon_color %}"
     stroke-width="1.7" stroke-linecap="round" stroke-linejoin="round">
    <polyline points="3 6 5 6 21 6"></polyline>
    <path d="M19 6v14a2 2 0 0 1-2 2H7a2 2 0 0 1-2-2V6m3 0V4a2 2 0 0 1 2-2h4a2 2 0 0 1 2 2v2"></path>
    <line x1="10" y1="11" x2="10" y2="17"></line><line x1="14" y1="11" x2="14" y2="17"></line>
</svg>
{% endblock delete_img_icon %}
</button>

irasaneh/comment/templates/comment/comments/edit_icon.html
{% load comment_tags %}
{% load i18n %}
<a title='{% trans "Edit comment" %}' class="js-comment-edit {% block edit_link_cls %}btn btn-link{% endblock edit_link_cls %}"
   href="{% url 'comment:edit' pk=comment.id %}?model_name={% get_model_name model_object %}&model_id={{ model_object.id }}&app_name={% get_app_name model_object %}&oauth={{oauth}}">
{% block edit_img_icon %}
<svg xmlns="http://www.w3.org/2000/svg" width="18" height="18" viewBox="0 0 24 24" fill="none"
     stroke="{% block edit_icon_color %}#00bc8c{% endblock edit_icon_color %}"
     stroke-width="1.7" stroke-linecap="round" stroke-linejoin="round" class="feather feather-edit">
    <path d="M11 4H4a2 2 0 0 0-2 2v14a2 2 0 0 0 2 2h14a2 2 0 0 0 2-2v-7"></path>
    <path d="M18.5 2.5a2.121 2.121 0 0 1 3 3L12 15l-4 1 1-4 9.5-9.5z"></path>
</svg>
{% endblock edit_img_icon %}
</a>

irasaneh/comment/templates/comment/comments/messages.html
{% if messages %}
{% for message in messages %}
    <div {% if message.tags %} class="alert alert-{{ message.tags }}" {% endif %}>
        {{ message }}
    </div>
    {% endfor %}
{% endif %}

irasaneh/comment/templates/comment/comments/parent_comment.html
{% load comment_tags %}
<div class="js-parent-comment {% block parent_comment_wrapper_cls %}text-wrap{% endblock parent_comment_wrapper_cls %}">
    {% include 'comment/comments/comment_body.html' with comment=comment %}
    <div class="js-replies {% block replies_wrapper_cls %} mr-5 my-4{% endblock replies_wrapper_cls %} d-none">
        {% get_comment_replies comment user as replies %}
        {% for comment in replies %}
            {% include 'comment/comments/child_comment.html' %}
        {% endfor %}
        {% include 'comment/comments/create_comment.html' with placeholder=placeholder %}
    </div>
    <hr/>
</div>

irasaneh/comment/templates/comment/comments/reject_icon.html
{% load comment_tags %}
{% load i18n %}
<button title="{% if comment.has_rejected_state %}{% trans "Flag rejected" %}{% else %}{% trans "Reject the flag" %}{% endif %}" class="js-flag-reject {% block reject_btn_cls %}btn btn-link{% endblock reject_btn_cls %}" data-state="{{ comment.flag.REJECTED }}" data-url="{% url 'comment:flag-change-state' pk=comment.id %}">

{% block reject_img_icon %}
<svg class="{% if comment.has_rejected_state %}flag-rejected{% endif %}"
     xmlns="http://www.w3.org/2000/svg" width="18" height="18" viewBox="0 0 24 24"
     fill="none" stroke="{% block reject_icon_color %}#E74C3C{% endblock reject_icon_color %}"
     stroke-width="1.7" stroke-linecap="round" stroke-linejoin="round">
     <path d="m19.216 15.194c0.31035 0.06374 0.55087-0.12433 0.77177-0.18337 4e-3 -0.0037 7e-3 -0.0065 9e-3 -0.0084 6e-3 -3.9981 3e-3 -8.0025 3e-3 -12.003 0 0-1 1-4 1s-5-2-8-2-4 1-4 1v12"></path>
     <line x1="4" x2="4" y1="22" y2="15"></line>
     <g transform="matrix(1.0063 0 0 1.0063 50.624 -.78936)">
      <g transform="matrix(1.1808 0 0 1.1808 55.855 .43703)">
       <path d="m-83.031 14.926 6.7248-6.7248"></path>
       <path d="m-76.306 14.926-6.7248-6.7248"></path>
      </g>
     </g>
</svg>
{% endblock reject_img_icon %}
</button>

irasaneh/comment/templates/comment/comments/resolve_icon.html
{% load comment_tags %}
{% load i18n %}
<button title="{% if comment.has_resolved_state %}{% trans "Flag resolved" %}{% else %}{% trans "Resolve the flag" %}{% endif %}" class="js-flag-resolve {% block resolved_btn_cls %}btn btn-link{% endblock resolved_btn_cls %}" data-state="{{ comment.flag.RESOLVED }}" data-url="{% url 'comment:flag-change-state' pk=comment.id %}">

{% block resolved_img_icon %}
<svg class="{% if comment.has_resolved_state %}flag-resolved{% endif %}"
     xmlns="http://www.w3.org/2000/svg" width="18" height="18" viewBox="0 0 24 24"
     fill="none" stroke="{% block resolved_icon_color %}#E74C3C{% endblock resolved_icon_color %}"
     stroke-width="1.7" stroke-linecap="round" stroke-linejoin="round">
     <path d="m11.939 20.395c-2.3228-3.8704-6.6445-2.2732-10.044-1.5539l0.10519-15.842h6c1.9144 0.42177 3.3887 1.4863 3.9187 3.1939"></path>
     <path d="m7.2106 9.7002 3.6287 5.1401 8.115-13.216" stroke-width="2.5"></path>
     <path d="m11.939 20.395c2.3228-3.8704 6.6445-2.2732 10.044-1.5539l-0.10519-15.841"></path>
</svg>
{% endblock resolved_img_icon %}
</button>

irasaneh/comment/templates/comment/comments/urlhash.html
{% load i18n %}
<a class="headerlink {% block urlhash_cls %}js-comment-urlhash{% endblock urlhash_cls %}" href="#{{ urlhash }}" title="{% trans 'Permalink to this comment' %}">
    {% block urlhash_icon %}
    ¶
    {% endblock urlhash_icon %}
</a>