irasaneh/VOD/urls.py
from django.urls import path
from .views import *


app_name = "VOD"

urlpatterns = [
    path('', ResanehList.as_view(), name='list'),
    path('<int:pk>', ResanehDetail.as_view(), name='detail'),

    path('advideo/', AdVideoList.as_view(), name='list-video'),
    path('advideo/<int:pk>', AdVideoDetail.as_view(), name='detail-video'),
    path('adbox/', AdBoxList.as_view(), name='list-box'),
    path('adbox/<int:pk>', AdBoxDetail.as_view(), name='detail-box'),
    path('adevent/', AdEventList.as_view(), name='list-event'),
    path('adevent/<int:pk>', AdEventDetail.as_view(), name='detail-event'),

    path('AdConnectionLog/', AdConnectionLogPost.as_view(), name='AdConnectionLog'),
    path('AdApplicationLog/', AdApplicationLogPost.as_view(), name='AdApplicationLog'),
    path('AdVideoLog/', AdVideoLogPost.as_view(), name='AdVideoLog'),
    path('AdVideoCounterLog/', AdVideoCounterLogPost.as_view(), name='AdVideoCounterLog'),

    path('AdMyBox/<int:pk>', AdMyBox.as_view(), name='AdMyBox'),
    path('AdMyResanehs/<str:phone>', AdMyResanehs.as_view(), name='AdMyResanehs'),
    # path('AdMyResanehs/<int:pk>', AdMyResanehs.as_view(), name='AdMyResanehs'),
    path('test/', testapi, name='test'),



]

irasaneh/config/urls.py
from django.contrib import admin
from django.urls import path, include
from rest_framework_simplejwt import views as jwt_views

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('home.urls')),
    path('mblog/', include('blog.urls')),
    path('account/', include('account.urls')),
    path('resaneh/', include('resaneh.urls')),
    path('dashboard/', include('dashboard.urls')),
    path('cities/', include('cities.urls')),
    path('summernote/', include('django_summernote.urls')),
    path('comment/', include('comment.urls')),
    path('ratings/', include('star_ratings.urls', namespace='ratings')),
    path('api-auth/', include('rest_framework.urls')),

    path('VOD/', include('VOD.urls')),
    path('VOD/token/', jwt_views.TokenObtainPairView.as_view(), name='token_obtain_pair'),
    path('VOD/token/refresh/', jwt_views.TokenRefreshView.as_view(), name='token_refresh'),

]


#در حالت دپلوی غیرفعال بشه
from django.conf import settings
from django.conf.urls.static import static

urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

irasaneh/dashboard/urls.py
from django.urls import path
from .views import *

app_name = "dashboard"
urlpatterns = [
    path('', dashboard, name='dashboard'),
    path('profile', profile, name='profile'),
    path('company', company, name='company'),
    path('changepass', changepass, name='changepass'),
    path('employee', employee, name='employee'),
    path('myofflineresaneh', myofflineresaneh, name='myofflineresaneh'),
    path('mydigitalresaneh', mydigitalresaneh, name='mydigitalresaneh'),

    path('vod', vodDashboard, name='vodDashboard'),
    path('vodResanehs', vodResanehs, name='vodResanehs'),
    path('vodResanehAdd', vodResanehAdd, name='vodResanehAdd'),
    path('vodResanehDelete/<int:pk>', vodResanehDelete, name="vodResanehDelete"),
    path('vodResanehUpdate/<slug:slug>', vodResanehUpdate, name="vodResanehUpdate"),
    path('vodVideos', vodVideos, name='vodVideos'),
    path('vodVideoAdd', vodVideoAdd, name='vodVideoAdd'),
    path('vodVideoUpdate/<int:pk>', vodVideoUpdate, name="vodVideoUpdate"),
    path('vodVideoDelete/<int:pk>', vodVideoDelete, name="vodVideoDelete"),
    path('vodBoxes', vodBoxes, name='vodBoxes'),
    path('vodBoxAdd', vodBoxAdd, name='vodBoxAdd'),
    path('vodBoxUpdate/<int:pk>', vodBoxUpdate, name="vodBoxUpdate"),
    path('vodBoxDelete/<int:pk>', vodBoxDelete, name="vodBoxDelete"),
    path('vodEvents', vodEvents, name='vodEvents'),
    path('vodEventAdd', vodEventAdd, name='vodEventAdd'),
    path('vodEventUpdate/<int:pk>', vodEventUpdate, name="vodEventUpdate"),
    path('vodEventDelete/<int:pk>', vodEventDelete, name="vodEventDelete"),

    path('charts', charts, name="charts"),
    path('lastlog', lastlog, name="lastlog"),
    path('chartjs', chartjs, name="chartjs"),
    path('flot', flot, name="flot"),
    path('inline', inline, name="inline"),


    path('Videos', Videos, name='Videos'),
    path('VideoAdd', VideoAdd, name='VideoAdd'),
    path('VideoUpdate/<int:pk>', VideoUpdate, name="VideoUpdate"),
    path('VideoDelete/<int:pk>', VideoDelete, name="VideoDelete"),

    path('ajax/load-counterChart/', load_counterChart, name='ajax_load_counterChart'),


]

irasaneh/hitcount/urls.py
from django.urls import path

from hitcount.views import HitCountJSONView

app_name = 'hitcount'

urlpatterns = [
    path('hit/ajax/', HitCountJSONView.as_view(), name='hit_ajax'),
]

irasaneh/home/urls.py
from django.urls import path
from .views import *

app_name = "home"
urlpatterns = [
    path('', homepage, name='homepage'),
    path('about', about, name='about'),
    path('contact', contact, name='contact'),
    path('faq', faq, name='faq'),
    path('termsAndconditions', termsAndconditions, name='termsAndconditions'),
    path('whoWeAre', whoWeAre, name='whoWeAre'),
]

irasaneh/resaneh/urls.py
from django.urls import path
from .views import *

app_name = "resaneh"
urlpatterns = [
    path('', resaneh, name='resaneh'),
    path('page/<int:page>', resaneh, name='resaneh'),
    path('<slug:slug>', resaneh, name='resaneh'),
    path('<slug:slug>/page/<int:page>', resaneh, name='resaneh'),
    path('details/<slug:slug>', details, name='details'),
    # path('category/<slug:slug>', category, name='category'),
    # path('category/<slug:slug>/page/<int:page>', category, name='category'),
    # path('search/', search, name='search'),
    # path('search/page/<int:page>', search, name='search'),
    path('ajax/search-similars/', search_similars, name='ajax_search_similars'),


    path('comparison/', comparison, name='comparison'),
    path('comparison/<slug:slug1>', comparison, name='comparison'),
    path('comparison/<slug:slug1>/<slug:slug2>', comparison, name='comparison'),
    path('comparison/<slug:slug1>/<slug:slug2>/<slug:slug3>', comparison, name='comparison'),
    path('comparison/<slug:slug1>/<slug:slug2>/<slug:slug3>/<slug:slug4>', comparison, name='comparison'),
]

irasaneh/VOD/models.py
from django.db import models
from django.utils import timezone
from extensions.utils import jalali_converter
from django.utils.html import format_html
from django.contrib.auth import get_user_model
from resaneh.models import Resaneh
from django.core.validators import FileExtensionValidator
from account.models import Company
# Create your models here.

class AdVideoType(models.Model):
    title = models.CharField(max_length=200, verbose_name="نوع ویدیو", blank=True)
    detail = models.TextField(verbose_name="جزییات بیشتر", blank=True)
    status = models. BooleanField(default=True, verbose_name="نمایش داده شود؟")
    created = models.DateTimeField(auto_now_add=True)

    class Meta:
        verbose_name = "نوع ویدیو"
        verbose_name_plural = "انواع ویدیو"

    def __str__(self):
        return str(self.title)


class AdVideo(models.Model):
    CONDITION_CHOICES = (
        ('p', 'پیش‌نویس'),
        ('d', 'در انتظار بررسی'),
        ('y', 'تایید شده'),
        ('n', 'رد شده'),
    )
    name = models.CharField(max_length=200, verbose_name="نام ویدیو", blank=True)
    type = models.ForeignKey(AdVideoType, verbose_name="نوع", blank=True, null=True, on_delete=models.SET_NULL,related_name="advideo")
    owner =  models.ForeignKey(get_user_model(), null=True, on_delete=models.SET_NULL, related_name="advideo", verbose_name="ایجاد کننده")
    company =  models.ForeignKey(Company, null=True, on_delete=models.SET_NULL, related_name="advideo", verbose_name="صاحب ویدیو", blank=True)#شرکت صاحب ویدیو
    status = models. BooleanField(default=True, verbose_name="نمایش داده شود؟")
    video = models.FileField(upload_to='advideos',null=True, validators=[FileExtensionValidator(allowed_extensions=['MOV','avi','mp4','webm','mkv','jpg'])], verbose_name="ویدیو", blank=True)

    condition = models.CharField(max_length=1, choices=CONDITION_CHOICES,default='p',verbose_name="وضعیت انتشار", blank=True)

    created = models.DateTimeField(auto_now_add=True)
    updated = models.DateTimeField(auto_now=True)

    class Meta:
        verbose_name = "ویدیو"
        verbose_name_plural = "ویدیوها"

    def __str__(self):
        return str(self.name)

    def mstatus(self):
        if self.status == True:
            a = "<img src='/static/admin/img/icon-yes.svg' alt='True'>"
        else:
            a = "<img src='/static/admin/img/icon-no.svg' alt='False'>"
        return format_html(a)
        # return format_html("<img style='width:55px;' src='{}'".format(self.thumbnail.url))


class AdBox(models.Model):
    owner =  models.ForeignKey(get_user_model(), null=True, on_delete=models.SET_NULL, related_name="adbox", verbose_name="ایجاد کننده", blank=True)
    name = models.CharField(max_length=200, verbose_name="نام باکس آگهی", blank=True)
    numberOfVideos = models.PositiveIntegerField(verbose_name="تعداد ویدیوها", blank=True)
    status = models.BooleanField(default=True, verbose_name="نمایش داده شود؟")
    order =  models.CharField(max_length=200, verbose_name="ترتیب نمایش فیلم‌ها", blank=True,help_text='اعداد را به انگلیسی وارد کنید و با - فاصله دهید.')
    created = models.DateTimeField(auto_now_add=True)
    updated = models.DateTimeField(auto_now=True)

    videos = models.ManyToManyField(AdVideo, verbose_name="ویدیوها", related_name="adbox")

    videos_list = models.CharField(max_length=200, verbose_name="ویدیو‌های مرتب شده", blank=True)

    class Meta:
        verbose_name = "باکس"
        verbose_name_plural = "باکس‌ها"

    # def save_related(self, request, form, formsets, change):
    #     super(AdBox, self).save_related(request, form, formsets, change)
    #     videos = self.videosvideo_id_list = list(videos.values_list('id', flat=True))
    #     orders = self.order
    #     orders_list = map(int, orders.split('-'))
    #     z = [x for _,x in sorted(zip(orders_list,video_id_list))]
    #     video_play_list = ','.join(map(str, z))
    #     # print(orders_list)
    #     # A = self.save()
    #     self.videos_list = video_play_list
    #     super(AdBox, self).save_related(request, form, formsets, change)



    def __str__(self):
        return str(self.name)

    # def save(self, *args, **kwargs):
    #     super(AdBox, self).save(*args, **kwargs)
    #     videos = self.videos
    #     video_id_list = list(videos.values_list('id', flat=True))
    #     orders = self.order
    #     orders_list = map(int, orders.split('-'))
    #     z = [x for _,x in sorted(zip(orders_list,video_id_list))]
    #     video_play_list = ','.join(map(str, z))
    #     # print(orders_list)
    #     # A = self.save()
    #     self.videos_list = video_play_list
    #     super(AdBox, self).save(*args, **kwargs)

    def mstatus(self):
        if self.status == True:
            a = "<img src='/static/admin/img/icon-yes.svg' alt='True'>"
        else:
            a = "<img src='/static/admin/img/icon-no.svg' alt='False'>"
        return format_html(a)




class AdEvent(models.Model):
    owner =  models.ForeignKey(get_user_model(), null=True, on_delete=models.SET_NULL, related_name="adevent", verbose_name="ایجاد کننده", blank=True)
    name = models.CharField(max_length=200, verbose_name="نام", blank=True)
    slug = models.SlugField(max_length=100, unique=True, verbose_name="آدرس")
    status = models. BooleanField(default=True, verbose_name="نمایش داده شود؟")
    detail = models.TextField(verbose_name="جزییات بیشتر", blank=True)
    media = models.ForeignKey(AdBox, null=True, on_delete=models.SET_NULL, related_name="adevent", verbose_name="باکس", blank=True)
    resaneh = models.ManyToManyField(Resaneh,related_name="adevent", verbose_name="رسانه", blank=True)
    startTime = models.TimeField(default=timezone.now, verbose_name="ساعت شروع")
    endTime = models.TimeField(default=timezone.now, verbose_name="ساعت پایان")
    startDate = models.DateTimeField(default=timezone.now, verbose_name="زمان شروع")
    endDate = models.DateTimeField(default=timezone.now, verbose_name="زمان پایان")
    created = models.DateTimeField(auto_now_add=True)
    updated = models.DateTimeField(auto_now=True)

    class Meta:
        verbose_name = "رویداد"
        verbose_name_plural = "رویدادها"

    def __str__(self):
        return str(self.name)

    def jstartDate(self):
        return jalali_converter(self.startDate).split(',')[0]
    jstartDate.short_description = "تاریخ شروع"

    def jendDate(self):
        return jalali_converter(self.endDate).split(',')[0]
    jendDate.short_description = "تاریخ پایان"

    def resaneh_active(self):
        return self.resaneh.filter(status='p')

    def mstatus(self):
        if self.status == True:
            a = "<img src='/static/admin/img/icon-yes.svg' alt='True'>"
        else:
            a = "<img src='/static/admin/img/icon-no.svg' alt='False'>"
        return format_html(a)


class AdConnectionLog(models.Model):
    resaneh = models.ForeignKey(Resaneh,verbose_name="رسانه",blank=True,on_delete=models.SET_NULL, related_name="adconnectionlog", null=True)
    detail = models.TextField(verbose_name="جزییات بیشتر", blank=True)
    created = models.DateTimeField(default=timezone.now,verbose_name="زمان ایجاد", blank=True)

    def jcreated(self):
        return jalali_converter(self.created)
    jcreated.short_description = "زمان ایجاد"


class AdApplicationLog(models.Model):
    resaneh = models.ForeignKey(Resaneh,verbose_name="رسانه",blank=True,on_delete=models.SET_NULL, related_name="adapplicationlog", null=True)
    name = models.CharField(max_length=200, verbose_name="نام", blank=True)
    detail = models.TextField(verbose_name="جزییات بیشتر", blank=True)
    created = models.DateTimeField(default=timezone.now,verbose_name="زمان ایجاد", blank=True)


class AdVideoLog(models.Model):
    resaneh = models.ForeignKey(Resaneh,verbose_name="رسانه",blank=True,on_delete=models.SET_NULL, related_name="advideolog", null=True)
    video = models.ForeignKey(AdVideo,verbose_name="ویدیو",blank=True,on_delete=models.SET_NULL, related_name="advideolog", null=True)
    box = models.ForeignKey(AdBox,verbose_name="باکس",blank=True,on_delete=models.SET_NULL, related_name="advideolog", null=True)
    name = models.CharField(max_length=200, verbose_name="نام", blank=True)
    detail = models.TextField(verbose_name="جزییات بیشتر", blank=True)
    created = models.DateTimeField(default=timezone.now,verbose_name="زمان ایجاد", blank=True)


class AdVideoCounterLog(models.Model):
    resaneh = models.ForeignKey(Resaneh,verbose_name="رسانه",blank=True,on_delete=models.SET_NULL, related_name="advideocounterlog", null=True)
    video = models.ForeignKey(AdVideo,verbose_name="ویدیو",blank=True,on_delete=models.SET_NULL, related_name="advideocounterlog", null=True)
    box = models.ForeignKey(AdBox,verbose_name="باکس",blank=True,on_delete=models.SET_NULL, related_name="advideocounterlog", null=True)
    detail = models.TextField(verbose_name="جزییات بیشتر", blank=True)
    created = models.DateTimeField(default=timezone.now,verbose_name="زمان ایجاد", blank=True)

irasaneh/dashboard/models.py
from django.db import models

# Create your models here.

irasaneh/comment/views/base.py
from django.views.generic import FormView

from comment.conf import settings
from comment.context import DABContext
from comment.responses import DABResponseData
from comment.messages import EmailInfo
from comment.service.email import DABEmailService
from comment.forms import CommentForm


class BaseCommentView(FormView, DABResponseData):
    form_class = CommentForm

    def get_context_data(self, **kwargs):
        context = super().get_context_data(**kwargs)
        context['comment_form'] = context.pop('form')
        context.update(DABContext(self.request))
        return context

    def get_form_kwargs(self):
        kwargs = super().get_form_kwargs()
        kwargs['request'] = self.request
        return kwargs


class CommentCreateMixin(BaseCommentView):
    email_service = None

    def _initialize_email_service(self, comment, request):
        self.email_service = DABEmailService(comment, request)

    def _send_notification_to_followers(self, comment, request):
        if settings.COMMENT_ALLOW_SUBSCRIPTION:
            self._initialize_email_service(comment, request)
            self.email_service.send_notification_to_followers()

    def perform_save(self, comment, request):
        comment.save()
        self._send_notification_to_followers(comment, request)
        comment.refresh_from_db()
        return comment

    def _handle_anonymous(self, comment, request, api=False):
        self._initialize_email_service(comment, request)
        self.email_service.send_confirmation_request(api=api)
        self.anonymous = True
        self.msg = EmailInfo.CONFIRMATION_SENT

    def perform_create(self, comment, request, api=False):
        if settings.COMMENT_ALLOW_ANONYMOUS and not comment.user:
            self._handle_anonymous(comment, request, api)
        else:
            comment = self.perform_save(comment, request)
        return comment

irasaneh/dashboard/templates/dashboard/Videos.html
{% extends 'dashboard/base.html' %}
{% load crispy_forms_tags %}

{% load static %}

{%block title%}|لیست ویدیو‌ها
{% endblock %}

{% block sidebar %}
{% include 'dashboard/sidebar.html' %}
{% endblock %}

{% block header %}
لیست ویدیو‌ها
{% endblock %}

{% block content %}
<div class="row">
<!-- modal -->
  <div class="modal fade" id="modal-default" style="display: none;" aria-hidden="true">
    <div class="modal-dialog">
      <div class="modal-content">
        <div class="modal-header">
          <h4 class="modal-title">حذف</h4>
          <button type="button" class="close" data-dismiss="modal" aria-label="Close">
            <span aria-hidden="true">×</span>
          </button>
        </div>
        <div class="modal-body">

        </div>
        <div class="modal-footer justify-content-between">
          <button type="button" class="btn btn-default shadow" data-dismiss="modal">بستن</button>
          <a type="button" class="delbut btn btn-danger" value="" href="">حذف</a>
        </div>
      </div>
      <!-- /.modal-content -->
    </div>
    <!-- /.modal-dialog -->
  </div>


  <div class="col-12">
    <div class="card">
      <div class="card-header">
        <h3 class="card-title mb-0 float-left pt-1">ویدیو‌های من</h3>

        <div class="card-tools mb-0 float-right">
          <div class="input-group input-group-sm" style="width: 150px;">
            <input type="text" name="table_search" class="form-control float-right" placeholder="جستجو">

            <div class="input-group-append">
              <button type="submit" class="btn btn-default"><i class="fas fa-search"></i></button>
            </div>
          </div>
        </div>
      </div>
      <!-- /.card-header -->
      <div class="card-body table-responsive p-0 table-striped" style="height: 300px;">
        <table class="table table-head-fixed">
          <thead>
            <tr class="small">
              <th>کد</th>
              <th>نام</th>
              <th>نوع</th>
              <th>ایجاد کننده</th>
              <th>رسانه‌دار</th>
              <th>فعال</th>
              <th>وضعیت</th>
              <!-- <th>لینک</th> -->
              <th>تاریخ ایجاد</th>
              ‍‍‍<th>ویرایش</th>‍
            </tr>
          </thead>
          <tbody>
            {% for video in videos %}
            <tr>
              <td>{{video.id}}</td>
              <td>{{video.name}}</td>
              <td>{{video.type}}</td>
              <td>{{video.owner}}</td>
              <td>{{video.company}}</td>
              <td>{{video.mstatus}}</td>
              <td>{{video.get_condition_display}}</td>
              <!-- <td class="text-break"><a href="{{video.video}}">{{video.video}}</a></td> -->
              <td>{{video.created}}</td>

              <td class="project-actions text-left">
                <a class="btn btn-primary btn-sm" href="{% if video.video %}{{ video.video.url }}{% endif %}" id="">
                  <i class="fas fa-folder">
                  </i>
                  مشاهده
                </a>
                <a class="btn btn-info btn-sm" href="{% url 'dashboard:VideoUpdate' video.id %}">
                  <i class="fas fa-pencil-alt">
                  </i>
                  ویرایش
                </a>
                <a class="del btn btn-danger btn-sm" data-toggle="modal" data-id="{{video.id}}" data-target="#modal-default" href="#">
                  <i class="fas fa-trash">
                  </i>
                  حذف
                </a>
              </td>
            </tr>
            {% empty %}
            <p class="pr-4 text-danger">محتوایی برای نمایش وجود ندارد</p>
            {% endfor %}

          </tbody>
        </table>
      </div>
      <!-- /.card-body -->
    </div>
    <!-- /.card -->
  </div>
</div>‍
<script type="text/javascript">

  $(document).on("click", ".del", function () {
       var delId = $(this).data('id');
       $('.delbut').attr('href', '/dashboard/VideoDelete/'+delId);
       $('.modal-body').html(`آیا از حذف کد ${delId} مطمئن هستید؟`)
  });

</script>

{% endblock %}

irasaneh/dashboard/templates/dashboard/changepass.html
{% extends 'dashboard/base.html' %}
{% load crispy_forms_tags %}

{% load static %}

{%block title%}|تغییر رمز ورود
{% endblock %}

{% block sidebar %}
{% include 'dashboard/sidebar.html' %}
{% endblock %}

{% block header %}
تغییر رمز ورود
{% endblock %}

{% block content %}

{% if messages %}
{% for message in messages %}
<div class="alert {% if message.tags %}alert-{{ message.tags }}{% endif %}" role="alert">{{ message }}</div>
{% endfor %}
{% endif %}

<div class="col-md-12">
  <div class="card card-danger">
    <div class="card-header">
      <h3 class="card-title mb-0 float-left">تغییر رمز</h3>
    </div>
    <div class="card-body">
      <form method="post" enctype="multipart/form-data">
        {% csrf_token %}
        {{form|crispy}}

        <button name="profile" class="btn btn-success">ارسال</button>
      </form>
    </div>
  </div>
</div>

{% endblock %}

irasaneh/dashboard/templates/dashboard/dashboard.html
{% extends 'dashboard/base.html' %}

{% load static %}

{%block title%}|داشبورد من
{% endblock %}

{% block sidebar %}
  {% include 'dashboard/sidebar.html' %}
{% endblock %}

{% block header %}
داشبورد
{% endblock %}

{% block content %}
{% if request.user.profile %}
<div class="row">
          <div class="col-lg-3 col-6">
            <!-- small box -->
            <div class="small-box bg-info">
              <div class="inner">
                <h3>{{cresanehs}}</h3>

                <p>تعداد رسانه‌ها</p>
              </div>
              <div class="icon">
                <i class="ion ion-bag"></i>
              </div>
              <a href="{% url 'dashboard:myofflineresaneh' %}" class="small-box-footer">اطلاعات بیشتر <i class="fas fa-arrow-circle-right"></i></a>
            </div>
          </div>
          <!-- ./col -->
          <div class="col-lg-3 col-6">
            <!-- small box -->
            <div class="small-box bg-success">
              <div class="inner">
                <h3>{{actives}}<sup style="font-size: 20px"></sup></h3>

                <p>تعداد رسانه‌های فعال</p>
              </div>
              <div class="icon">
                <i class="ion ion-stats-bars"></i>
              </div>
              <a href="#" class="small-box-footer">اطلاعات بیشتر <i class="fas fa-arrow-circle-right"></i></a>
            </div>
          </div>

          {% if request.user.profile.position == 'm' %}
          <!-- ./col -->
          <div class="col-lg-3 col-6">
            <!-- small box -->
            <div class="small-box bg-warning">
              <div class="inner">
                <h3>{{cemployees}}</h3>

                <p>تعداد کارمندان</p>
              </div>
              <div class="icon">
                <i class="ion ion-person-add"></i>
              </div>
              <a href="{% url 'dashboard:employee'%}" class="small-box-footer">اطلاعات بیشتر <i class="fas fa-arrow-circle-right"></i></a>
            </div>
          </div>
          {% endif %}

          <!-- ./col -->
          <div class="col-lg-3 col-6">
            <!-- small box -->
            <div class="small-box bg-danger">
              <div class="inner">
                <h3>{{hits}}</h3>

                <p>تعداد بازدید‌های کل رسانه‌ها</p>
              </div>
              <div class="icon">
                <i class="ion ion-pie-graph"></i>
              </div>
              <a href="#" class="small-box-footer">اطلاعات بیشتر <i class="fas fa-arrow-circle-right"></i></a>
            </div>
          </div>
          <!-- ./col -->
        </div>
{% else %}
<div class="text-danger">
<h4>برای استفاده از امکانات سایت ابتدا باید حساب کاربری خود را تکمیل کنید!</h4>
<a href="{% url 'dashboard:profile' %}">تکمیل پروفایل</a>
</div>
{% endif %}
{% endblock %}

irasaneh/dashboard/templates/dashboard/myofflineresaneh.html
{% extends 'dashboard/base.html' %}
{% load crispy_forms_tags %}

{% load static %}

{%block title%}|رسانه‌ها
{% endblock %}

{% block sidebar %}
  {% include 'dashboard/sidebar.html' %}
{% endblock %}

{% block header %}
رسانه‌های آفلاین
{% endblock %}

{% block content %}
<div class="row">
          <div class="col-12">
            <div class="card">
              <div class="card-header">
                <h3 class="card-title mb-0 float-left pt-1">رسانه‌های آفلاین من</h3>

                <div class="card-tools mb-0 float-right">
                  <div class="input-group input-group-sm" style="width: 150px;">
                    <input type="text" name="table_search" class="form-control float-right" placeholder="جستجو">

                    <div class="input-group-append">
                      <button type="submit" class="btn btn-default"><i class="fas fa-search"></i></button>
                    </div>
                  </div>
                </div>
              </div>
              <!-- /.card-header -->
              <div class="card-body table-responsive p-0 table-striped" style="height: 300px;">
                <table class="table table-head-fixed">
                  <thead>
                    <tr class="small">
                      <th>کد</th>
                      <th>عنوان</th>
                      <th>رسانه‌دار</th>
                      <th>ایجاد‌کننده</th>
                      <th>مالک</th>
                      <th>وضعیت</th>
                      <th>لینک</th>
                    </tr>
                  </thead>
                  <tbody>
                    {% for resaneh in resanehs %}
                    <tr>
                      <td>{{resaneh.code}}</td>
                      <td>{{resaneh.name}}</td>
                      <td>{{resaneh.company}}</td>
                      <td>{{resaneh.creator}}</td>
                      <td>{{resaneh.owner}}</td>
                      <td>{{resaneh.get_status_display}}</td>
                      <td><a href="{% url 'resaneh:details' resaneh.slug %}">بیشتر</a></td>
                    </tr>
                    {% endfor %}
                  </tbody>
                </table>
              </div>
              <!-- /.card-body -->
            </div>
            <!-- /.card -->
          </div>
        </div>‍
{% endblock %}